all:
	reveal-md ./ --disableAutoOpen

serveall: 
	reveal-md -w ./

print: d3js_openstreetmap_talk.md
	reveal-md d3js_openstreetmap_talk.md --print d3js_openstreetmap_talk.pdf

clean:
	rm -rf *.pdf

.PHONY: all serveall clean
